### ISSUE TITLE
please remove the extra period from the orange map .array variable

### ISSUE THREAD

**Issue by Rpascar1** [learn-co-curriculum/ruby-enumerables-generalized-map-and-reduce-lab#5]

**Comment by sgharms** [comment]
Hi @Rpascar1 

When I searched all the files in this repo I found no occurrence of `..` anywhere in any file. Similarly, there's no occurrence of orange in any of the files either. Could you have meant to have opened this issue on a different repository? If so, could you please record it there?

![image](https://user-images.githubusercontent.com/50019/63587828-f2aedb00-c572-11e9-831f-24051f9dbc6a.png)

Please re-open if I've missed something.

**Comment by Rpascar1** [comment]
Hi Steven I'm confused - please pull up the lesson enumerable family tree
the image is orange. There is a .array var listed. I may have raised the
issue but had the wrong tab open.

**Comment by sgharms** [comment]
@Rpascar1 Got it. This issue is opened on ruby-enumerables-generalized-map-and-reduce-lab. I've confirmed this issue in the other repo and we'll get an updated image out ASAP.
